### ISSUE TITLE
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'created_utc')

### ISSUE THREAD

**Issue by TheLazySquid** [web-temps/RedditBot-TemplateJS#2]
After adding in the environment variables and running the program, it yields this error: 
```
Unhandled rejection TypeError: Cannot read properties of undefined (reading 'created_utc')
    at assignFirstUTC (path\to\project\src\util\inboxStreamGenerator.js:41:44)
    at tryCatcher (path\to\project\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (path\to\project\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (path\to\project\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (path\to\project\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (path\to\project\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (path\to\project\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (path\to\project\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (path\to\project\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (path\to\project\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (node:internal/timers:464:21)
```

I have changed nothing in the project aside from adding the file "pw.env".

**Comment by essovius** [comment]
> After adding in the environment variables and running the program, it yields this error:
> 
> ```
> Unhandled rejection TypeError: Cannot read properties of undefined (reading 'created_utc')
>     at assignFirstUTC (path\to\project\src\util\inboxStreamGenerator.js:41:44)
>     at tryCatcher (path\to\project\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (path\to\project\node_modules\bluebird\js\release\promise.js:547:31)
>     at Promise._settlePromise (path\to\project\node_modules\bluebird\js\release\promise.js:604:18)
>     at Promise._settlePromise0 (path\to\project\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (path\to\project\node_modules\bluebird\js\release\promise.js:729:18)
>     at _drainQueueStep (path\to\project\node_modules\bluebird\js\release\async.js:93:12)
>     at _drainQueue (path\to\project\node_modules\bluebird\js\release\async.js:86:9)
>     at Async._drainQueues (path\to\project\node_modules\bluebird\js\release\async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (path\to\project\node_modules\bluebird\js\release\async.js:15:14)
>     at processImmediate (node:internal/timers:464:21)
> ```
> 
> I have changed nothing in the project aside from adding the file "pw.env".

Any update on this? Did you find the solution?

**Comment by TheLazySquid** [comment]
> Any update on this? Did you find the solution?

Nope, unfortunately not
